### ISSUE TITLE
Bad caption

### ISSUE THREAD

**Issue by dljzx** [dabasajay/Image-Caption-Generator#1]
Bad caption like this
![output_111766423_4522d36e56](https://user-images.githubusercontent.com/47135039/58165013-7974c300-7cb9-11e9-808c-5ac731a051b8.jpg)

**Comment by dabasajay** [comment]
How many epochs did you train for and what were your training and validation loss?

**Comment by dljzx** [comment]
Only 15 epochs and I forgot the loss. Is that too low? How can I train more epochs?

**Comment by dljzx** [comment]
> How many epochs did you train for and what were your training and validation loss?

Only 15 epochs and I forgot the loss. Is that too low? How can I train more epochs?

**Comment by dabasajay** [comment]
I'll get back to you with some possible reasons for this and solutions positively by Wednesday, 29 May'19

**Comment by dabasajay** [comment]
I have added a new model and batch processing of data during training. Now the model performs significantly better. Try out yourself and let me know if something goes wrong again

**Comment by dljzx** [comment]
> I have added a new model and batch processing of data during training. Now the model performs significantly better. Try out yourself and let me know if something goes wrong again

I tried but  got keyerror like this
Traceback (most recent call last):
  File "train_val.py", line 15, in <module>
    X1train, X2train, max_length = loadTrainData(config)
  File "E:\github\Image-Caption-Generator\utils\load_data.py", line 186, in loadTrainData
    train_image_features = load_image_features(config['model_data_path']+'features_'+str(config['model_type'])+'.pkl', train_image_ids)
  File "E:\github\Image-Caption-Generator\utils\load_data.py", line 78, in load_image_features
    features = {_id: all_features[_id] for _id in ids}
  File "E:\github\Image-Caption-Generator\utils\load_data.py", line 78, in <dictcomp>
    features = {_id: all_features[_id] for _id in ids}
KeyError: '172092461_a9a9762e13'
