### ISSUE TITLE
error while training

### ISSUE THREAD

**Issue by ROHITDH** [dabasajay/Image-Caption-Generator#9]

**Comment by PranayAren** [comment]
I am facing this issue too, could you please help me out , as if what could
i do to train this model

**Comment by ROHITDH** [comment]
@PranayAren, you must install these version packages to work, in latest version we will get that training error.

Python - 3.6.7
Numpy - 1.16.4
Tensorflow - 1.13.1
Keras - 2.2.4
nltk - 3.2.5
PIL - 4.3.0
Matplotlib - 3.0.3
tqdm - 4.28.1

**Comment by PranayAren** [comment]
Thank you for your suggestion
